INSERT INTO users (username,password_hash,role) VALUES ('anthony','$2a$10$B06mpNtTh.wVqZ0lQqZuB.4OIeSndryMgs9NEWiuX5xE9xBprJa62','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('ben','$2a$10$xjkY08HI4K7Y/A42N/k/xOcXK4K/WFlbGHmBgL5CkgetnoDo2w5J6','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('bobby','$2a$10$UFcfseryfJGNE31NEDjp3Ozc4a7fgoe0VPCDEZeV.rTqooTs8jYKu','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('kaleb','$2a$10$HygU75rIzT29bl0AvdzZHu8MjJafuKgKTOchpkmRz1Hb5R1DDUg/a','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('michele','$2a$10$lCG0OxbCTXRRVUlL.nRo8Oh6Q1uaHesfDejxAmYe/iDSrhG0QR5ce','ROLE_USER');

INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours, brewery_history, brewer_id, active) VALUES ('Brewery On Main', '923 Main Street', 'Philadelphia', 'PA', '19032', '111-111-1111', 'Breweryonmain@email.com', '09:00,17:00,09:00,17:00,09:00,17:00,09:00,17:00,09:00,17:00,0,0,0,0', 'Placeholder text for the history of Brewery On Main', 3, true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Homer''s Brewery', '293 Broad Street', 'Anaheim', 'CA', '78392', '222-222-2222', 'Homersbrewer@email.com', '12:00,20:00,12:00,20:00,12:00,20:00,12:00,20:00,12:00,20:00,12:00,20:00,12:00,17:00', 'Placeholder text for the history of Homer''s Brewery', 3, true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Liberty Brewery', '14 Hay Road', 'Houston', 'TX', '38394', '333-333-3333', 'Libertybrewery@email.com', '14:00,20:00,14:00,20:00,14:00,20:00,14:00,20:00,14:00,20:00,14:00,20:00,0,0', 'Placeholder text for the history of Liberty Brewery', 3, true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Tap Brewery', '35 Beach Street', 'Orlando', 'FL', '49384', '444-444-4444', 'Tapbrewery@email.com', '16:00,02:00,16:00,02:00,16:00,02:00,16:00,02:00,16:00,02:00,16:00,02:00,0,0', 'Placeholder text for the history of Tap Brewery', 3, true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Freedom Brewery', '2244 Independence Blvd', 'Kansas City','MO', '64030', '555-555-5555', 'Freedombrewery@email.com', '09:00,17:00,09:00,17:00,09:00,17:00,09:00,17:00,09:00,17:00,0,0,0,0', 'Placeholder text for the history of Freedom Brewery', 3, 
true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Silver Mine Brewery', '10 Mine Lane', 'Red Lodge', 'MT', '09068', '666-666-6666', 'SilverBrewery@email.com', '12:00,20:00,12:00,20:00,12:00,20:00,12:00,20:00,12:00,20:00,12:00,20:00,12:00,17:00', 'Placeholder text for the history of Silver Brewery', 3, true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Poor Mice Brewery', '4554 Sococo Street', 'Valley Forge', 'PA', '19460', '777-777-7777', 'Poormice@email.com', '14:00,20:00,14:00,20:00,14:00,20:00,14:00,20:00,14:00,20:00,14:00,20:00,0,0', 'Placeholder text for the history Of Poor Mice Brews', 3, true);
INSERT INTO breweries (brewery_name, brewery_address, brewery_city, brewery_state, brewery_zip, brewery_phone, brewery_email, brewery_hours,  brewery_history, brewer_id, active) VALUES ('Scarlet Brewery', '183 Labrador Lane', 'Hershey', 'PA', '17017', '888-888-8888', 'Scarletbrewery@email.com', '16:00,02:00,16:00,02:00,16:00,02:00,16:00,02:00,16:00,02:00,16:00,02:00,0,0', 'Placeholder text for the history of Scarlet Brewery', 3, 
true);

INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Hefeweizen', 'Delicious', '4.1', 'Hefeweizen', 'Hefeweizen_Glass.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Angelic Brew', 'Halo not included', '5.1', 'Hefeweizen', 'Hefeweizen_Glass.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Never Enough', 'This beer will keep you coming back for more', '5.6', 'Hefeweizen', 'Hefeweizen_Glass.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('It''s 5:00', 'It''s always 5:00 in Margaritaville, and yes they have beer!', '5.0', 'Hefeweizen', 'Hefeweizen_Glass.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Life''s A Beach', 'Beaches are for relaxing, so relax your taste buds as well', '5.2', 'Hefeweizen', 'Hefeweizen_Glass.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Black Sails', 'Every pirate loves this Hefeweizen', '5.4', 'Hefeweizen', 'Hefeweizen_Glass.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Canadian Lager', 'Tastes like maple syrup!', '5.1', 'Lager', 'lager.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Not a Logger', 'It''s a Lager, not a logger. Logger''s do love the taste though!', '5.0', 'Lager', 'lager.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Brown Gold', 'Brown is the new gold after all', '4.9', 'Lager', 'lager.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Heaven''s Brew', 'A beer worthy of it''s name!', '5.2', 'Lager', 'lager.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('One More', 'You might as well have one more, and it might as well be one of these.', '5.1', 'Lager', 'lager.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Without A Paddle', 'No paddle? No Problem. Forget about your problems with our unique brew!', '5.4', 'Lager', 'lager.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Devil''s IPA', 'An IPA inspired by the Devil', '7.7', 'IPA', 'IPA.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Witches Brew', 'Magical', '6.4', 'IPA', 'IPA.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Imperial IPA', 'Will make you feel like an emperor! No empire necessary.', '7.3', 'IPA', 'IPA.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Nightshift IPA', 'This IPA is fantastic day or night', '8.1', 'IPA', 'IPA.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('The Best IPA', 'Definitely the best IPA you''ve ever tasted!', '6.7', 'IPA', 'IPA.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Stone Cold IPA', 'Colder than the Rockies', '7.8', 'IPA', 'IPA.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Special Wit', 'A special Wit', '4.8', 'Wit', 'belgianwitbiersmall.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Ocean Delight', 'Refreshing', '5.5','Wit', 'belgianwitbiersmall.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Neon Light', 'Got troubles? Neon Light is always the solution.', '5.0','Wit', 'belgianwitbiersmall.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Not My Fault', 'Don''t blame me, I just encouraged you.', '4.9','Wit', 'belgianwitbiersmall.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Parrot''s Head', 'Or is it parrot head? Enough of these and you won''t remember either!', '5.3','Wit', 'belgianwitbiersmall.jpg');
INSERT INTO beer (beer_name, beer_description, beer_abv, beer_type, beer_image) VALUES ('Come Sail Away', 'Escape the grind and set sail with this remarkable Wit', '5.1','Wit', 'belgianwitbiersmall.jpg');

INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (1, 11, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (1, 13, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (1, 21, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (2, 5, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (2, 12, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (2, 17, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (3, 8, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (3, 10, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (3, 18, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (4, 7, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (4, 15, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (4, 20, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (5, 3, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (5, 14, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (5, 23, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (6, 4, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (6, 16, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (6, 22, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (7, 6, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (7, 9, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (7, 19, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (8, 1, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (8, 2, true);
INSERT INTO beer_inventory (brewery_id, beer_id, active) VALUES (8, 24, true);

INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (1, 1, 'Greating tasting beer');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (7, 5, 'Greating tasting beer');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (13, 5, 'Greating tasting beer');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (24, 5, 'Greating tasting beer');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (1, 2, 'Okay');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (2, 2, 'Okay');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (14, 2, 'Okay');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (18, 2, 'Okay');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (3, 4, 'Better than average');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (8, 4, 'Better than average');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (15, 4, 'Better than average');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (23, 4, 'Better than average');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (2, 1, 'Too sweet for me');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (4, 1, 'Too sweet for me');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (16, 1, 'Too sweet for me');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (17, 1, 'Too sweet for me');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (5, 3, 'Average tasting');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (9, 3, 'Average tasting');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (17, 3, 'Average tasting');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (22, 3, 'Average tasting');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (3, 2, 'I''ll pass on this one next time');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (6, 2, 'I''ll pass on this one next time');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (16, 2, 'I''ll pass on this one next time');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (18, 2, 'I''ll pass on this one next time');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (7, 4, 'Fantastic!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (10, 4, 'Fantastic!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (19, 4, 'Fantastic!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (21, 4, 'Fantastic!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (4, 2, 'Not the worst beer I''ve had, but far from the best.');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (8, 2, 'Not the worst beer I''ve had, but far from the best.');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (15, 2, 'Not the worst beer I''ve had, but far from the best.');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (20, 2, 'Not the worst beer I''ve had, but far from the best.');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (9, 5, 'Best beer I''ve had');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (11, 5, 'Best beer I''ve had');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (20, 5, 'Best beer I''ve had');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (21, 5, 'Best beer I''ve had');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (5, 4, 'Absolutely delicious');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (10, 4, 'Absolutely delicious');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (14, 4, 'Absolutely delicious');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (22, 4, 'Absolutely delicious');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (11, 2, 'Not bad');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (12, 2, 'Not bad');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (19, 2, 'Not bad');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (23, 2, 'Not bad');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (6, 1, 'Horrible!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (12, 1, 'Horrible!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (13, 1, 'Horrible!');
INSERT INTO beer_reviews (beer_id, beer_rating, beer_review) VALUES (24, 1, 'Horrible!');

INSERT INTO user_reviews (user_id, review_id) VALUES (4, 1);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 2);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 3);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 4);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 5);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 6);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 7);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 8);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 9);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 10);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 11);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 12);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 13);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 14);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 15);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 16);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 17);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 18);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 19);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 20);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 21);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 22);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 23);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 24);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 25);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 26);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 27);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 28);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 29);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 30);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 31);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 32);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 33);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 34);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 35);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 36);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 37);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 38);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 39);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 40);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 41);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 42);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 43);
INSERT INTO user_reviews (user_id, review_id) VALUES (7, 44);
INSERT INTO user_reviews (user_id, review_id) VALUES (8, 45);
INSERT INTO user_reviews (user_id, review_id) VALUES (4, 46);
INSERT INTO user_reviews (user_id, review_id) VALUES (5, 47);
INSERT INTO user_reviews (user_id, review_id) VALUES (6, 48);

INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (1, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (2, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (3, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (4, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (5, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (6, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (7, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (8, 'taps.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (1, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (2, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (3, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (4, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (5, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (6, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (7, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (8, 'taps2.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (1, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (2, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (3, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (4, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (5, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (6, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (7, 'casks.jpg');
INSERT INTO brewery_images (brewery_id, brewery_image) VALUES (8, 'casks.jpg');